/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI;
import Model.Savings;

/**
 *
 * @author sukhadapradhan
 */
public class ViewJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewJpanel
     */
    
    Savings product;
    public ViewJpanel(Savings product) {
        initComponents();
        
        this.product = product;
        
        displayDemographic();
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        txtFirstname2 = new javax.swing.JTextField();
        lblFirstname = new javax.swing.JLabel();
        txtFirstname3 = new javax.swing.JTextField();
        lblLastname = new javax.swing.JLabel();
        lblphonenum = new javax.swing.JLabel();
        lblDOB = new javax.swing.JLabel();
        txtFirstname = new javax.swing.JTextField();
        txtFirstname1 = new javax.swing.JTextField();
        lblDOB1 = new javax.swing.JLabel();
        txtFirstname4 = new javax.swing.JTextField();

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 0, 21)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Savings Account");

        txtFirstname2.setEditable(false);
        txtFirstname2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstname2ActionPerformed(evt);
            }
        });

        lblFirstname.setText("Bank Name");

        txtFirstname3.setEditable(false);
        txtFirstname3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstname3ActionPerformed(evt);
            }
        });

        lblLastname.setText("Routing Number");

        lblphonenum.setText("Account Number");

        lblDOB.setText("Account Balance");

        txtFirstname.setEditable(false);
        txtFirstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstnameActionPerformed(evt);
            }
        });

        txtFirstname1.setEditable(false);
        txtFirstname1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstname1ActionPerformed(evt);
            }
        });

        lblDOB1.setText("Account Type");

        txtFirstname4.setEditable(false);
        txtFirstname4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFirstname4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblphonenum)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFirstname2, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblDOB)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFirstname3, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(lblDOB1)
                                        .addGap(18, 18, 18)
                                        .addComponent(txtFirstname4, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(159, 159, 159)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblFirstname)
                                    .addComponent(lblLastname))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtFirstname1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(lblTitle)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFirstname, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(lblFirstname)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLastname)
                    .addComponent(txtFirstname1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblphonenum)
                    .addComponent(txtFirstname2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDOB)
                    .addComponent(txtFirstname3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtFirstname4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDOB1))
                .addContainerGap(62, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtFirstname2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstname2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstname2ActionPerformed

    private void txtFirstname3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstname3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstname3ActionPerformed

    private void txtFirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstnameActionPerformed

    private void txtFirstname1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstname1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstname1ActionPerformed

    private void txtFirstname4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFirstname4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstname4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblDOB;
    private javax.swing.JLabel lblDOB1;
    private javax.swing.JLabel lblFirstname;
    private javax.swing.JLabel lblLastname;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblphonenum;
    private javax.swing.JTextField txtFirstname;
    private javax.swing.JTextField txtFirstname1;
    private javax.swing.JTextField txtFirstname2;
    private javax.swing.JTextField txtFirstname3;
    private javax.swing.JTextField txtFirstname4;
    // End of variables declaration//GEN-END:variables

    private void displayDemographic() {
        
        
        txtFirstname.setText(product.getFirstname());
        txtFirstname1.setText(product.getLastname());
        txtFirstname2.setText(product.getPhone());
        txtFirstname3.setText(product.getDOB());
        txtFirstname4.setText(product.getAge());
        
        
        
        
        
    }
}
